---
title: "Compound Poisson Processes"
author: "Noah Gblonyah, Seth Okyere, and Michael Throolin"
date: "10 December 2021"
output: 
  pdf_document: 
      number_sections: true
header-includes:
   - \usepackage{amsmath}
   - \usepackage{amsthm}
   - \usepackage[style=authoryear, backend=bibtex]{biblatex}
   - \usepackage{biblatex}
   - \addbibresource{bibliography.bib}
bibliography: bibliography.bib
---
\newtheorem{theorem}{Theorem}[section]
\newtheorem{definition}{Definition}[section]
\newtheorem{example}{Example}[section]

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Concept

\begin{definition}[Counting Processes]
A random process $\{N(t), t \in [0,\infty) \}$ is a counting process if,
\begin{enumerate}
\item $N(0) = 0$.
\item $N(t) \in \{0,1,2,3,4,...\}$ and is non-decreasing.
\end{enumerate}
\end{definition}

\begin{definition}[Poisson Processes]
A counting process $N(t)$ is a poisson process with rate $\lambda$ if,
\begin{enumerate}
\item $N(t)$ has independent increments. That is the set $N(t_j+s_j)-N(t_j) ,~ j \in \{0,1,2,...,n\}$ is independent for each non-overlapping increment $(t_j, t_j+s_j]$.
\item For all $ t \geq 0$ and $h >0$ ,  $N(t+h) -N(t)  \sim POIS(\Lambda)$ where $\Lambda = \int_t^{t+h} \lambda (z) dz$.
\end{enumerate}
\end{definition}

\begin{definition}[Compound Poisson Process]
A compound poisson process S(t) is defined as follows:
\begin{enumerate}
\item For $t>0, S(t) = \sum_{i=1}^{N(t)} X_i$, where $N(t)$ is a poisson process with rate function $\lambda$,
\item All random variables $X_i$ and $\{N(t), t>0 \}$ are independent and identically distributed,
\item $N(t) =0 \implies S(0) = 0$.
\end{enumerate}
\end{definition}

# Examples and Exploration

# References

---
nocite: '@*'
...